# Generated by Django 5.2.5 on 2025-08-28 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_alter_startupproject_status_delete_projectstatus"),
        ("projects", "0005_alter_startupproject_status_delete_projectstatus"),
    ]

    operations = []
