# Generated by Django 5.2.5 on 2025-08-27 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_projectstatus_status"),
        ("projects", "0005_alter_startupproject_status_delete_projectstatus"),
    ]

    operations = []
